### ISSUE TITLE
咨询

### ISSUE THREAD

**Issue by bluemsn** [ZengTianShengZ/My-Blog#4]
Hello , 你好， 是否有兴趣考虑新的工作机会， 我们是阿里巴巴新零售事业群-CBU体验技术团队， 如有兴趣，可加微信聊聊哈， 或者交个朋友【basen2013】

**Comment by ZengTianShengZ** [comment]
> Hello , 你好， 是否有兴趣考虑新的工作机会， 我们是阿里巴巴新零售事业群-CBU体验技术团队， 如有兴趣，可加微信聊聊哈， 或者交个朋友【basen2013】

杭州暂时不考虑哈
